'use client'
import { createContext, useContext, useState } from 'react'

const LanguageContext = createContext()

export const translations = {
    tr: {
        // Topbar
        topbarWelcome: 'Ödüllü Danışmanlık Firmasına Hoş Geldiniz',
        workingHours: 'Çalışma Saatleri: 09:00 - 18:00',
        // Header
        getInTouch: 'İletişime Geç',
        // Navigation
        navHome: 'Ana Sayfa',
        navPages: 'Sayfalar',
        navAbout: 'Hakkımızda',
        navServices: 'Hizmetler',
        navCase: 'Projeler',
        navBlog: 'Blog',
        navContact: 'İletişim',
        navTeamMember: 'Ekip Üyeleri',
        navTeamDetails: 'Ekip Detayı',
        navPricing: 'Fiyatlandırma',
        navCareer: 'Kariyer',
        navAwards: 'Ödüller',
        navMissionVision: 'Misyon & Vizyon',
        navFaqs: 'SSS',
        navOurService: 'Hizmetlerimiz',
        navOurService2: 'Danışmanlık Hizmetleri',
        navServiceDetails: 'Hizmet Detayı',
        navCaseStudy1: 'Proje Çalışması 01',
        navCaseStudy2: 'Proje Çalışması 02',
        navCaseDetails: 'Proje Detayı',
        navBlogStandard: 'Blog',
        navBlogDetails: 'Blog Detayı',
        // Hero
        heroSubtitle: 'Konaklama Sektörü Danışmanlık Firması',
        heroTitle: 'Modern İş',
        heroTitleAnd: 'Danışmanlığı',
        heroWord1: 'Hizmetleri',
        heroWord2: 'Çözümleri',
        heroWord3: 'Stratejisi',
        heroWord4: 'Denetimleri',
        heroDesc: 'Otel yatırımı, marka entegrasyonu, gelir yönetimi ve HIP ile turizm ve otelcilikte sahadan gelen stratejik danışmanlık sunuyoruz.',
        heroBtn: 'Hizmetleri Keşfet',
        heroVideo: 'Videoyu İzle',
        handwritingQuote: '"Başarınız için elimizden gelenin en iyisini sağlıyoruz"',
        marqueeText: 'Hospitality Global Experience Works & Green Horizon Hotels EcoSphere Consultance',
        // Section 1 - Features
        feat1Title: 'Otel Yatırım & Fizibilite',
        feat1Desc: 'Piyasa, talep ve finansal geri dönüş analizleriyle yatırım kararınızı veriye dayandırıyoruz.',
        feat1Item1: 'Yatırım fizibilitesi',
        feat1Item2: 'Teşvik ve belgelendirme',
        feat1Item3: 'Proje planlama ve yönetimi',
        feat2Title: 'HIP & Operasyonel Mükemmellik',
        feat2Desc: 'Hotel Improvement Plan ile gelir, maliyet ve süreçleri ölçülebilir biçimde iyileştiriyoruz.',
        feat2Item1: 'Gelir ve fiyatlandırma',
        feat2Item2: 'Operasyon ve kalite',
        feat2Item3: 'Kanal ve dijital satış',
        feat3Title: 'Marka & Yönetim Entegrasyonu',
        feat3Desc: 'Uluslararası marka alımı, franchising ve stratejik yönetimle otelinizi konumlandırıyoruz.',
        feat3Item1: 'Marka seçimi ve tescil',
        feat3Item2: 'Satış ve pazarlama yapısı',
        feat3Item3: 'Genel yönetim danışmanlığı',
        // Section 2 - About
        aboutSubtitle: 'hakkımızda',
        aboutTitle: 'Birlikte Daha Aydınlık Bir Gelecek İnşa Ediyor ve',
        aboutTitleSpan: 'İşinizi Büyütüyoruz',
        missionTitle: 'Misyonumuz',
        missionText: 'Otelcilik sanatını yeniden tanımlamak, veriyi bilgelikle birleştirerek sürdürülebilir başarıya dönüştürmek. Her oteli yalnızca bugünün rekabetine değil, yarının belirsizliğine karşı da güçlendirmek.',
        visionTitle: 'Vizyonumuz',
        visionText: 'Otelcilik sektöründe fark yaratan, özgün, sahici ve bilge bir yol arkadaşı olarak; veriyi bilgelikle, stratejiyi hikâyeyle, operasyonu sanatla buluşturmak.',
        learnMore: 'Hakkımızda Daha Fazla',
        // Section 3 - Services
        servicesSubtitle: 'otel yatırım ve yönetim danışmanlığı',
        servicesTitle: 'Otelcilikte Stratejiden Sahaya Uzman Destek',
        servicesDesc: 'Yatırım fizibilitesinden marka entegrasyonuna, gelir yönetiminden denetim ve HIP uygulamalarına kadar otelciliğin tüm değer zincirinde yanınızdayız.',
        satisfiedClients: 'Tamamlanan Proje & Otel',
        exploreServices: 'Tüm Hizmetleri Keşfet',
        service1Title: 'Otel Yatırım & Fizibilite Danışmanlığı',
        service1Desc: 'Talep, rekabet ve finansal modelleme ile yatırımınızın doğruluğunu güçlendiriyoruz.',
        service2Title: 'Marka Entegrasyonu & Franchising',
        service2Desc: 'Marka belirleme, hukuki koruma ve uluslararası zincirlerle stratejik işbirlikleri.',
        service3Title: 'Gelir Yönetimi & Satış-Pazarlama',
        service3Desc: 'Fiyatlandırma, kanal karması, RMS/CRM uyumu ve doğrudan satışlarla sürdürülebilir kârlılık.',
        service4Title: 'HIP, Denetim & Sürdürülebilirlik',
        service4Desc: 'Hotel Improvement Plan, operasyonel ve mali denetim ile kalite ve risk yönetimi.',
        service5Title: 'Otel Alım/Satım/Kiralama Aracılık Danışmanlığı',
        service5Desc: 'Otelcilik sektöründe yatırımcı ile otel sahibi arasındaki kritik köprüyü kuruyoruz. Otel satışları, kiralamaları ve işletme devri gibi tüm süreçlerde uzman aracılık hizmeti sunarak taraflar için en uygun zemini hazırlıyoruz.',
        readMore: 'Devamını Oku',
        // Section 4 - Process
        processSubtitle: 'çalışma süreci',
        processTitle: 'Fikirden Uygulamaya',
        processTitleSpan: 'Danışmanlık Sürecimiz',
        step1: 'Adım 01',
        step1Title: 'Keşif & Değerlendirme',
        step1Desc: 'Bu ilk aşamada müşterinin ihtiyaçlarını, zorluklarını ve hedeflerini anlıyoruz. Danışmanlar derinlemesine analiz yapıyor.',
        step1Item1: 'Paydaş Görüşmeleri & Veri Toplama',
        step1Item2: 'Kapsamlı İş Analizi',
        step2: 'Adım 02',
        step2Title: 'Strateji Geliştirme',
        step2Desc: 'Toplanan veriler ışığında özelleştirilmiş stratejiler ve çözüm yolları belirliyoruz.',
        step2Item1: 'Özel Strateji Planlaması',
        step2Item2: 'Risk Değerlendirmesi ve Yönetimi',
        step3: 'Adım 03',
        step3Title: 'Uygulama & Yürütme',
        step3Desc: 'Geliştirilen stratejileri adım adım hayata geçiriyor, süreçleri takip ediyoruz.',
        step3Item1: 'Proje Yönetimi & Koordinasyon',
        step3Item2: 'Kaynak Optimizasyonu',
        step4: 'Adım 04',
        step4Title: 'İzleme & Sürekli İyileştirme',
        step4Desc: 'Sonuçları sürekli ölçüyor ve gerekli iyileştirmeleri yaparak uzun vadeli başarıyı güvence altına alıyoruz.',
        step4Item1: 'Performans Metrikleri Takibi',
        step4Item2: 'Sürekli Optimizasyon',
        // Section 5 - Projects
        project1Title: 'İş Performansını Optimize Etme',
        projectTag1: 'Kurumsal',
        projectTag2: 'İş',
        projectTag3: 'Finans',
        // Section 6 - Team
        teamMarquee: 'uzman ekibimizle tanışın',
        teamSubtitle: 'Ekibimizle Tanışın',
        teamTitle: 'Uzman Ekip',
        teamTitleSpan: 'Üyeleri',
        exploreTeam: 'Tüm Üyeleri Görüntüle',
        consultant: 'İş Danışmanı',
        // Section 7 - Testimonials  
        testimonialSubtitle: 'müşteri yorumları',
        testimonialTitle: 'Müşterilerimizin',
        testimonialTitleSpan: 'Görüşleri',
        // Section 8 - Counter
        counterSubtitle: 'başarı rakamlarımız',
        counterTitle: 'Güvenilir Bir Danışmanlık Firmasını Seçmek',
        counterTitleSpan: 'İşletmenizi Dönüştürür',
        counter1: 'Tamamlanan Proje',
        counter2: 'Uzman Danışman',
        counter3: 'Ülkede Faaliyet',
        counter4: 'Memnun Müşteri',
        // Section 9 - Blog
        blogSubtitle: 'son haberler',
        blogTitle: 'En Son Blog',
        blogTitleSpan: 'Yazılarımız',
        readMoreLink: 'Devamını Oku',
        // Section 10 - Partners
        partnerSubtitle: 'iş ortaklarımız',
        partnerTitle: 'Güvenilen',
        partnerTitleSpan: 'İş Ortakları',
        // Section 11 - FAQ
        faqTitle: 'Sıkça Sorulan',
        faqTitleSpan: 'Sorular',
        s2FaqSubtitle: 'Sıkça Sorulan Sorular',
        s2FaqTitle: 'Danışmanlık Hakkında',
        s2FaqTitleSpan: 'Merak Edilenler',
        s2Faq1Q: 'Oteller için hangi hizmetleri sunuyorsunuz?',
        s2Faq1A: 'Yatırım fizibilitesinden operasyonel denetime, marka entegrasyonundan gelir yönetimine kadar geniş bir yelpazede stratejik danışmanlık sunuyoruz.',
        s2Faq2Q: 'Danışmanlık süreci nasıl başlar?',
        s2Faq2A: 'Öncelikle işletmenizin mevcut durumunu analiz eden bir keşif toplantısı yapıyoruz. Ardından hedeflerinize uygun bir strateji yol haritası belirliyoruz.',
        s2Faq3Q: 'Sadece kurumsal zincirlerle mi çalışıyorsunuz?',
        s2Faq3A: 'Hayır. Butik otellerden resortlara, apart otellerden uluslararası zincirlere kadar konaklama sektörünün her ölçeğinde hizmet veriyoruz.',
        s2Faq4Q: 'Hotel Improvement Plan (HIP) nedir?',
        s2Faq4A: 'HIP, otelinizin performansını röntgen gibi taradığımız ve veriye dayalı iyileştirme planları sunduğumuz özel bir performans artırma metodolojimizdir.',
        // Section 12 - CTA
        ctaTitle: 'Danışmanlık Hizmetlerimize Başlamaya Hazır mısınız?',
        ctaBtn: 'Ücretsiz Danışın',
        // Footer
        footerServices: 'Hizmetlerimiz',
        footerQuickLinks: 'Hızlı Bağlantılar',
        footerService1: 'Otel Yatırım Danışmanlığı',
        footerService2: 'Marka Entegrasyonu',
        footerService3: 'Otel Yönetim Danışmanlığı',
        footerService4: 'Otel Denetim Danışmanlığı',
        footerService5: 'HIP - Hotel Improvement Plan',
        footerLink1: 'Hakkımızda',
        footerLink2: 'Kariyer Fırsatları',
        footerLink3: 'Başvurular',
        footerLink4: 'İletişim',
        footerLink5: 'Proje Çalışmaları',
        footerNewsletterDesc: 'Dijital pazarlama alanındaki en son trendlerden haberdar olmak ve özel ipuçları almak için bültenimize abone olun.',
        footerEmailPlaceholder: 'E-posta Adresiniz',
        footerSubscribe: 'Abone Ol',
        footerCTA1Caption: 'Ekip Üyesi Olmak İster misiniz?',
        footerCTA1Desc: 'Her zaman yetenekli adaylar arıyoruz',
        footerCTA1Btn: 'Hemen Başla',
        footerCTA2Caption: 'Kaliteli Danışmanlığa mı İhtiyacınız Var?',
        footerCTA2Desc: 'Her zaman yetenekli adaylar arıyoruz',
        footerCTA2Btn: 'Danışmanlık Al',
        footerCTA3Caption: 'İş Fırsatı mı Arıyorsunuz?',
        footerCTA3Desc: 'Her zaman yetenekli adaylar arıyoruz',
        footerCTA3Btn: 'Bize Katılın',
        footerCopyright: 'Tüm Hakları Saklıdır',
        footerTerms: 'Kullanım Koşulları',
        footerPrivacy: 'Gizlilik Politikası',
        // Contact info
        contactUs: 'İletişim',
        address: 'Adres',
        email: 'E-posta',
        call: 'Telefon',
        // Our Service 02 Page
        s2Subtitle: 'neden bizi seçmelisiniz',
        s2Title: 'İş Başarınız İçin',
        s2TitleSpan: 'Eşsiz Uzmanlık',
        s2Desc: 'Müşterilerimizin hızla gelişen bir pazarda başarılı olmalarına yardımcı olan olağanüstü hizmet ve kişiselleştirilmiş stratejiler sunmaya kararlıyız.',
        s2Item1: 'Bizi Seçmek İçin Deneyim, Uzmanlık, Sonuçlar',
        s2Item2: 'İş Danışmanlığı Mükemmelliği İçin Akıllı Seçim',
        s2Explore: 'Hizmetlerimizi Keşfedin',
        s2SmartChoice: 'İş Danışmanlığı Mükemmelliği İçin Akıllı Seçim',
        s2Solution1Title: 'Özelleştirilmiş Çözümler',
        s2Solution1Desc: 'Her müşterinin benzersiz zorluklarını ve hedeflerini ele alan kişiselleştirilmiş stratejiler sunuyoruz.',
        s2Solution2Title: 'Veri Odaklı Yaklaşım',
        s2Solution2Desc: 'Eyleme geçirilebilir stratejiler oluşturmak için veri analitiği ve pazar araştırmasından yararlanıyoruz.',
        s2Solution3Title: 'Sürdürülebilir Sonuçlar',
        s2Solution3Desc: 'Sadece anlık zorlukları çözmekle kalmayan, uzun vadeli başarı getiren stratejilere odaklanıyoruz.',
        s2ConsultingSubtitle: 'danışmanlık hizmetleri',
        s2ConsultingTitle: 'İşinizi ve Satışlarınızı Büyütmek İçin',
        s2ConsultingTitleSpan: 'Kaliteli Hizmet',
        s2ManagementTitle: 'Yönetim Danışmanlığı',
        s2ManagementDesc: 'İşletmelerin potansiyelini açığa çıkaran profesyonel yönetim danışmanlığı.',
        s2ResourcesTitle: 'Kaynak Danışmanlığı',
        s2ResourcesDesc: 'Organizasyonel yapıyı ve kaynak yönetimini optimize etmek için tasarlanmış çözümler.',
        s2MarketingTitle: 'Pazarlama Danışmanlığı',
        s2MarketingDesc: 'Pazarlama çabalarınızı analiz ediyor ve iyileştirme alanlarını belirliyoruz.',
        s2FinancialTitle: 'Finansal Danışmanlık',
        s2FinancialDesc: 'Uzman finansal planlama, bütçe ve risk yönetimi desteği sağlıyoruz.',
        s2DigitalTitle: 'Dijital Dönüşüm',
        s2DigitalDesc: 'İşletmelere yeni teknolojilerin ve dijital araçların benimsenmesinde rehberlik ediyoruz.',
        s2OperationsTitle: 'Operasyon Yönetimi',
        s2OperationsDesc: 'Verimliliği artırmak ve maliyetleri düşürmek için iç süreçleri optimize ediyoruz.',
        s2FaqSubtitle: 'SSS',
        s2FaqTitle: 'Sıkça Sorulan',
        s2FaqTitleSpan: 'Sorular',
        s2Faq1Q: 'İş danışmanlığı nedir?',
        s2Faq1A: 'Sürecimiz genellikle iş ihtiyaçlarınızı ve hedeflerinizi değerlendirdiğimiz bir keşif aşamasıyla başlar, ardından uygulama ve sürekli izleme gelir.',
        s2Faq2Q: 'Danışmanlık süreci nasıl işler?',
        s2Faq2A: 'Strateji geliştirme, uygulama ve sonuçların takibi aşamalarından oluşan sistematik bir yaklaşım izliyoruz.',
        s2Faq3Q: 'Hangi tür işletmelerle çalışıyorsunuz?',
        s2Faq3A: 'Startup\'lardan büyük kurumsal yapılara kadar geniş bir yelpazedeki işletmelere hizmet veriyoruz.',
        s2Faq4Q: 'Hizmetlerinizin maliyeti ne kadar?',
        s2Faq4A: 'Maliyetler projenin kapsamına ve ihtiyaç duyulan uzmanlık seviyesine göre değişiklik göstermektedir.',
        s2SatisfiedCustomer: 'Müşteri Memnuniyeti',
        s2SatisfiedDesc: 'Hizmetlerimizden Memnun Kalan Müşteriler',
        s2Marquee1: 'Özel Bir Hizmete mi İhtiyacınız Var?',
        s2MarqueeContact: 'İletişime Geçin',
        s2Marquee2: 'Ekibimize Katılmak İster misiniz?',
        s2MarqueeJoin: 'Bize Katılın',
        s2TestimonialSubtitle: 'müşteri yorumları',
        s2TestimonialTitle: 'Müşterilerimiz Bizim Hakkımızda',
        s2TestimonialTitleSpan: 'Ne Diyor?',
        s2TestimonialDesc: 'İşletmelerin uzun vadeli hedeflerine ulaşmaları ve sürdürülebilir büyüme sağlamaları için net ve uygulanabilir stratejiler geliştirmelerine yardımcı oluyoruz.',
        whyFieldTitle: 'Gerçek Saha Deneyimi',
        whyFieldDesc: 'Sadece teorik danışmanlık sunmuyoruz; 40 yıllık sektörel deneyimden gelen bilgelikle yanınızdayız.',
        whyResultsTitle: 'Sonuç Odaklı Yaklaşım',
        whyResultsDesc: '"Otel iyi görünüyor mu?" diye değil, "Para kazanıyor mu?" diye soruyoruz. Her adım ölçülebilir.',
        whyServiceTitle: 'Kapsamlı Hizmet Yelpazesi',
        whyServiceDesc: 'Yatırım fizibilitesinden HIP\'e kadar otelciliğin tüm boyutlarında sizinleyiz.',
        whyGlobalTitle: 'Küresel ve Yerel Perspektif',
        whyGlobalDesc: 'Marriott, Hilton ve Accor gibi dev markalarla doğrudan çalışma deneyimine sahibiz.',
        faq1Q: 'MISIONES kimlerle çalışır?',
        faq1A: 'Otel yatırımcıları, girişimciler, mevcut otel işletmecileri ve tüm paydaşlarla çalışıyoruz.',
        faq2Q: 'HIP nedir ve kimler içindir?',
        faq2A: 'HIP (Hotel Improvement Plan), gelir kayıplarını ve operasyonel verimsizlikleri tespit edip çözen özel bir danışmanlık paketidir.',
        faq3Q: 'Danışmanlık süreci nasıl başlar?',
        faq3A: 'Ücretsiz bir ön görüşme ile başlıyoruz. Otelin mevcut durumunu, hedeflerini ve sorunlarını dinliyoruz.',
        faq4Q: 'Uluslararası otel markalarıyla çalışma deneyiminiz var mı?',
        faq4A: 'Evet. Marriott, Hilton, Wyndham, Accor ve daha birçok marka ile doğrudan çalışma deneyimimiz bulunmaktadır.',
        faq5Q: 'Sadece otellerle mi çalışıyorsunuz?',
        faq5A: 'Ana uzmanlığımız konaklama sektörüdür, ancak karma projeler için de danışmanlık sunuyoruz.',
        faq6Q: 'Danışmanlık sonrası uygulama takibi yapıyor musunuz?',
        faq6A: 'Evet. Performans göstergelerini takip ederek ve periyodik toplantılarla uygulama sonuçlarını aktif olarak izliyoruz.',
        contactTitle: 'Danışmanlık Talebi Gönderin',
        contactDesc: 'Projeniz, sorunuz veya işbirliği teklifiniz için bize yazın. En kısa sürede size dönüş yapacağız.',
        msgReceived: 'Mesajınız Alındı!',
        msgSuccess: 'En kısa sürede sizinle iletişime geçeceğiz.',
        formName: 'Ad Soyad *',
        formPhone: 'Telefon *',
        formEmail: 'E-posta *',
        formSubject: 'Konu',
        formMsg: 'Mesajınızı buraya yazın...',
        formSend: 'Mesajı Gönder',
        formOr: 'Veya doğrudan yazın: ',
    },
    en: {
        // Topbar
        topbarWelcome: 'Welcome to Award Winning Consulting Agency',
        workingHours: 'Working Hours: 09am - 06pm',
        // Header
        getInTouch: 'Get In Touch',
        // Navigation
        navHome: 'Home',
        navPages: 'Pages',
        navAbout: 'About',
        navServices: 'Services',
        navCase: 'Case',
        navBlog: 'Blog',
        navContact: 'Contact',
        navTeamMember: 'Team Member',
        navTeamDetails: 'Team Details',
        navPricing: 'Pricing Table',
        navCareer: 'Career',
        navAwards: 'Awards',
        navMissionVision: 'Mission Vision',
        navFaqs: 'FAQs',
        navOurService: 'Our Service',
        navOurService2: 'Our Service 02',
        navServiceDetails: 'Service Details',
        navCaseStudy1: 'Case Study 01',
        navCaseStudy2: 'Case Study 02',
        navCaseDetails: 'Case Details',
        navBlogStandard: 'Blog Standard',
        navBlogDetails: 'Blog Details',
        // Hero
        heroSubtitle: 'Hospitality Consulting Agency',
        heroTitle: 'Modern Business',
        heroTitleAnd: 'Consulting',
        heroWord1: 'Services',
        heroWord2: 'Solutions',
        heroWord3: 'Strategy',
        heroWord4: 'Audits',
        heroDesc: 'Strategic hospitality consulting across investment, brand integration, revenue management and HIP — grounded in field experience.',
        heroBtn: 'Explore Services',
        heroVideo: 'Watch Video',
        handwritingQuote: '"We provide our best for your success"',
        marqueeText: 'Hospitality Global Experience Works & Green Horizon Hotels EcoSphere Consultance',
        // Section 1 - Features
        feat1Title: 'Hotel Investment & Feasibility',
        feat1Desc: 'We ground your investment decisions in market, demand and financial return analysis.',
        feat1Item1: 'Investment feasibility',
        feat1Item2: 'Incentives & certification',
        feat1Item3: 'Project planning & management',
        feat2Title: 'HIP & Operational Excellence',
        feat2Desc: 'Hotel Improvement Plan to measurably lift revenue, cost control and processes.',
        feat2Item1: 'Revenue & pricing',
        feat2Item2: 'Operations & quality',
        feat2Item3: 'Channel & digital sales',
        feat3Title: 'Brand & Management Integration',
        feat3Desc: 'International brand acquisition, franchising and strategic leadership for your hotel.',
        feat3Item1: 'Brand selection & registration',
        feat3Item2: 'Sales & marketing structure',
        feat3Item3: 'General management advisory',
        // Section 2 - About
        aboutSubtitle: 'about company',
        aboutTitle: 'We Work For Building a Brighter Future Together and',
        aboutTitleSpan: 'Grow Business',
        missionTitle: 'Our Mission',
        missionText: 'To redefine the art of hospitality; combining data with wisdom to turn it into sustainable success. To strengthen each hotel not just against today\'s competition, but also against tomorrow\'s uncertainty.',
        visionTitle: 'Our Vision',
        visionText: 'To be a unique, authentic, and wise companion that makes a difference in hospitality; bringing together data with wisdom, strategy with storytelling, and operations with artistry.',
        learnMore: 'Learn More About Us',
        // Section 3 - Services
        servicesSubtitle: 'hotel investment & management consulting',
        servicesTitle: 'Expert Support From Strategy to Field Execution',
        servicesDesc: 'From feasibility and brand integration to revenue management, audits and HIP — we cover the full hospitality value chain.',
        satisfiedClients: 'Projects & Hotels Delivered',
        exploreServices: 'Explore All Services',
        service1Title: 'Hotel Investment & Feasibility',
        service1Desc: 'Demand, competition and financial modelling to validate and strengthen your investment.',
        service2Title: 'Brand Integration & Franchising',
        service2Desc: 'Brand definition, legal protection and strategic partnerships with international chains.',
        service3Title: 'Revenue Management & Sales-Marketing',
        service3Desc: 'Pricing, channel mix, RMS/CRM alignment and direct booking growth for sustainable profit.',
        service4Title: 'HIP, Audit & Sustainability',
        service4Desc: 'Hotel Improvement Plan plus operational and financial audits, quality and risk control.',
        service5Title: 'Hotel Acquisition / Sale / Lease Brokerage',
        service5Desc: 'Establishing a critical bridge between investors and hotel owners in the hospitality sector. We provide expert brokerage services in hotel sales, leases and management transfers.',
        readMore: 'Read More',
        // Section 4 - Process
        processSubtitle: 'working process',
        processTitle: 'From Concept to Execution',
        processTitleSpan: 'Our Consulting Process',
        step1: 'Step 01',
        step1Title: 'Discovery & Assessment',
        step1Desc: 'This initial phase involves understanding the client\'s needs, challenges, and goals. Consultants conduct in-depth analysis.',
        step1Item1: 'Stakeholder Interviews & Data Gathering',
        step1Item2: 'Comprehensive Business Analysis',
        step2: 'Step 02',
        step2Title: 'Strategy Development',
        step2Desc: 'Based on gathered data, we identify customized strategies and solution paths.',
        step2Item1: 'Custom Strategy Planning',
        step2Item2: 'Risk Assessment and Management',
        step3: 'Step 03',
        step3Title: 'Implementation & Execution',
        step3Desc: 'We implement the developed strategies step by step and monitor the processes.',
        step3Item1: 'Project Management & Coordination',
        step3Item2: 'Resource Optimization',
        step4: 'Step 04',
        step4Title: 'Monitoring & Continuous Improvement',
        step4Desc: 'We continuously measure results and make necessary improvements to ensure long-term success.',
        step4Item1: 'Performance Metrics Tracking',
        step4Item2: 'Continuous Optimization',
        // Section 5 - Projects
        project1Title: 'Optimizing Business Performance',
        projectTag1: 'Corporate',
        projectTag2: 'Business',
        projectTag3: 'Finance',
        // Section 6 - Team
        teamMarquee: 'meet our expert team',
        teamSubtitle: 'Meet Our Team',
        teamTitle: 'Expert Team',
        teamTitleSpan: 'Members',
        exploreTeam: 'Explore All Members',
        consultant: 'Business Consultant',
        // Section 7 - Testimonials  
        testimonialSubtitle: 'client testimonials',
        testimonialTitle: 'Our Clients',
        testimonialTitleSpan: 'Testimonials',
        // Section 8 - Counter
        counterSubtitle: 'our success numbers',
        counterTitle: 'Choosing a Trusted Consulting Firm',
        counterTitleSpan: 'Transforms Your Business',
        counter1: 'Projects Completed',
        counter2: 'Expert Consultants',
        counter3: 'Countries Served',
        counter4: 'Satisfied Clients',
        // Section 9 - Blog
        blogSubtitle: 'latest news',
        blogTitle: 'Latest Blog',
        blogTitleSpan: 'Articles',
        readMoreLink: 'Read More',
        // Section 10 - Partners
        partnerSubtitle: 'our partners',
        partnerTitle: 'Trusted',
        partnerTitleSpan: 'Partners',
        // Section 11 - FAQ
        faqTitle: 'Frequently Asked',
        faqTitleSpan: 'Questions',
        s2FaqSubtitle: 'Frequently Asked Questions',
        s2FaqTitle: 'About Our',
        s2FaqTitleSpan: 'Consulting',
        s2Faq1Q: 'What services do you offer for hotels?',
        s2Faq1A: 'We offer a wide range of strategic consulting from investment feasibility to operational audits, brand integration to revenue management.',
        s2Faq2Q: 'How does the consulting process begin?',
        s2Faq2A: 'We start with a discovery meeting to analyze your current situation. Then, we define a strategic roadmap tailored to your goals.',
        s2Faq3Q: 'Do you only work with corporate chains?',
        s2Faq3A: 'No. We serve all scales of the hospitality sector, from boutique hotels to resorts and international chains.',
        s2Faq4Q: 'What is the Hotel Improvement Plan (HIP)?',
        s2Faq4A: 'HIP is our methodology where we scan your hotel performance and provide data-driven improvement plans.',
        // Section 12 - CTA
        ctaTitle: 'Ready to Start with Our Consulting Services?',
        ctaBtn: 'Free Consultation',
        // Footer
        footerServices: 'Our Services',
        footerQuickLinks: 'Quick Links',
        footerService1: 'Hotel Investment Consulting',
        footerService2: 'Brand Integration',
        footerService3: 'Hotel Management Consulting',
        footerService4: 'Hotel Audit Consulting',
        footerService5: 'HIP - Hotel Improvement Plan',
        footerLink1: 'About Company',
        footerLink2: 'Career Options',
        footerLink3: 'Applications',
        footerLink4: 'Contact Us',
        footerLink5: 'Case Studies',
        footerNewsletterDesc: 'Stay up-to-date with the latest trends in digital marketing and receive exclusive tips and insights by subscribing to our newsletter.',
        footerEmailPlaceholder: 'Email Address',
        footerSubscribe: 'Subscribe',
        footerCTA1Caption: 'Become a Team Member?',
        footerCTA1Desc: 'We are always looking for talented members',
        footerCTA1Btn: 'Get Started',
        footerCTA2Caption: 'Need Quality Consultations?',
        footerCTA2Desc: 'We are always looking for talented members',
        footerCTA2Btn: 'Get Consultation',
        footerCTA3Caption: 'Are You Looking For A Job?',
        footerCTA3Desc: 'We are always looking for talented members',
        footerCTA3Btn: 'Join With Us',
        footerCopyright: 'All Rights Reserved',
        footerTerms: 'Terms & Conditions',
        footerPrivacy: 'Privacy Policy',
        // Contact info
        contactUs: 'Contact Us',
        address: 'Address',
        email: 'Email',
        call: 'Call',
        // Our Service 02 Page
        s2Subtitle: 'why choose us',
        s2Title: 'Unmatched Expertise for Your',
        s2TitleSpan: 'Business Success',
        s2Desc: 'We are committed to delivering exceptional service and personalized strategies that help our clients succeed in a rapidly evolving marketplace.',
        s2Item1: 'Experience, Expertise, Results to Choose Us',
        s2Item2: 'Smart Choice for Business Consulting Excellence',
        s2Explore: 'Explore Our Services',
        s2SmartChoice: 'Smart Choice for Business Consulting Excellence',
        s2Solution1Title: 'Customized Solutions',
        s2Solution1Desc: 'We provide tailored strategies that address the unique challenges and goals of each client.',
        s2Solution2Title: 'Data-Driven Approach',
        s2Solution2Desc: 'We leverage data analytics and market research to create actionable strategies.',
        s2Solution3Title: 'Sustainable Results',
        s2Solution3Desc: 'We focus on long-term success by developing strategies that position businesses for growth.',
        s2ConsultingSubtitle: 'consulting services',
        s2ConsultingTitle: 'The Quality Consulting Service to Grow',
        s2ConsultingTitleSpan: 'Your Business',
        s2ManagementTitle: 'Management Consulting',
        s2ManagementDesc: 'Our Management Consulting services unlock business potential.',
        s2ResourcesTitle: 'Resources Consulting',
        s2ResourcesDesc: 'Designed to optimize how organizations manage their resources.',
        s2MarketingTitle: 'Marketing Consulting',
        s2MarketingDesc: 'Analyzing current marketing efforts and identifying improvement goals.',
        s2FinancialTitle: 'Financial Consulting',
        s2FinancialDesc: 'Provides expert financial planning, budget and risk management.',
        s2DigitalTitle: 'Digital Transformation',
        s2DigitalDesc: 'Guiding businesses through adoption of new technologies and digital tools.',
        s2OperationsTitle: 'Operations Management',
        s2OperationsDesc: 'Analyzing and optimizing internal processes to improve efficiency.',
        s2FaqSubtitle: 'FAQs',
        s2FaqTitle: 'Asked',
        s2FaqTitleSpan: 'Questions',
        s2Faq1Q: 'What is business consulting?',
        s2Faq1A: 'Our process typically starts with a discovery phase, where we assess your business needs and goals, followed by implementation.',
        s2Faq2Q: 'How does the consulting process work?',
        s2Faq2A: 'We follow a systematic approach comprising strategy development, implementation, and performance tracking.',
        s2Faq3Q: 'What types of businesses do you work with?',
        s2Faq3A: 'We work with a wide range of businesses, from startups to large corporate entities.',
        s2Faq4Q: 'How much do your services cost?',
        s2Faq4A: 'Costs vary depending on the project scope and the level of expertise required.',
        s2SatisfiedCustomer: 'Customer Satisfaction',
        s2SatisfiedDesc: 'Customers are Satisfied with the Services',
        s2Marquee1: 'Need Any Custom Service?',
        s2MarqueeContact: 'Contact Us',
        s2Marquee2: 'Want to Join Our Team?',
        s2MarqueeJoin: 'Join Our Team',
        s2TestimonialSubtitle: 'client testimonials',
        s2TestimonialTitle: 'What Our Clients Say',
        s2TestimonialTitleSpan: 'about Us',
        s2TestimonialDesc: 'Helping businesses develop clear, actionable strategies to achieve long-term goals and sustainable growth.',
        whyFieldTitle: 'Real Field Experience',
        whyFieldDesc: 'We don’t just offer theoretical consulting; we are with you with wisdom gained from 40 years of sectoral experience.',
        whyResultsTitle: 'Result-Oriented Approach',
        whyResultsDesc: 'We don’t ask "Does the hotel look good?", we ask "Is it making money?". Every step is measurable.',
        whyServiceTitle: 'Comprehensive Service Range',
        whyServiceDesc: 'We are with you in all dimensions of hospitality, from investment feasibility to HIP.',
        whyGlobalTitle: 'Global and Local Perspective',
        whyGlobalDesc: 'We have direct experience working with giant brands like Marriott, Hilton, and Accor.',
        faq1Q: 'Who does MISIONES work with?',
        faq1A: 'We work with hotel investors, entrepreneurs, existing hotel operators, and all stakeholders.',
        faq2Q: 'What is HIP and who is it for?',
        faq2A: 'HIP (Hotel Improvement Plan) is a special consulting package that identifies and resolves revenue losses and operational inefficiencies.',
        faq3Q: 'How does the consulting process begin?',
        faq3A: 'We start with a free preliminary meeting. We listen to the hotel\'s current status, goals, and problems.',
        faq4Q: 'Do you have experience working with international hotel brands?',
        faq4A: 'Yes. We have direct experience working with Marriott, Hilton, Wyndham, Accor, and many other brands.',
        faq5Q: 'Do you only work with hotels?',
        faq5A: 'Our core expertise is the hospitality sector, but we also offer consulting for mixed-use projects.',
        faq6Q: 'Do you follow up on implementation after consulting?',
        faq6A: 'Yes. We actively monitor implementation results by tracking performance indicators and periodic meetings.',
        contactTitle: 'Send a Consultation Request',
        contactDesc: 'Send us your project, question, or collaboration proposal. We will get back to you as soon as possible.',
        msgReceived: 'Message Received!',
        msgSuccess: 'We will contact you as soon as possible.',
        formName: 'Full Name *',
        formPhone: 'Phone *',
        formEmail: 'Email *',
        formSubject: 'Subject',
        formMsg: 'Write your message here...',
        formSend: 'Send Message',
        formOr: 'Or write directly: ',
    },
    ar: {
        topbarWelcome: 'مرحبا بكم في وكالة الاستشارات الحائزة على جوائز',
        workingHours: 'ساعات العمل: 09:00 ص - 06:00 م',
        getInTouch: 'تواصل معنا',
        navHome: 'الرئيسية',
        navPages: 'الصفحات',
        navAbout: 'من نحن',
        navServices: 'الخدمات',
        navCase: 'المشاريع',
        navBlog: 'المدونة',
        navContact: 'اتصل بنا',
        navTeamMember: 'أعضاء الفريق',
        navTeamDetails: 'تفاصيل الفريق',
        navPricing: 'الأسعار',
        navCareer: 'الوظائف',
        navAwards: 'الجوائز',
        navMissionVision: 'المهام والرؤية',
        navFaqs: 'الأسئلة الشائعة',
        navOurService: 'خدماتنا',
        navOurService2: 'خدماتنا 02',
        navServiceDetails: 'تفاصيل الخدمة',
        navCaseStudy1: 'دراسة حالة 01',
        navCaseStudy2: 'دراسة حالة 02',
        navCaseDetails: 'تفاصيل الحالة',
        navBlogStandard: 'المدونة العادية',
        navBlogDetails: 'تفاصيل المدونة',
        heroSubtitle: 'وكالة استشارات الضيافة',
        heroTitle: 'الأعمال الحديثة',
        heroTitleAnd: 'الاستشارات',
        heroWord1: 'خدمات',
        heroWord2: 'حلول',
        heroWord3: 'إستراتيجية',
        heroWord4: 'تدقيقات',
        heroDesc: 'نقدم استشارات استراتيجية ميدانية في مجال الضيافة عبر الاستثمار، دمج العلامات التجارية، إدارة الإيرادات وتحسين الفنادق.',
        heroBtn: 'استكشف الخدمات',
        heroVideo: 'شاهد الفيديو',
        handwritingQuote: '"نحن نقدم أفضل ما لدينا لنجاحك"',
        marqueeText: 'Hospitality Global Experience Works & Green Horizon Hotels EcoSphere Consultance',
        feat1Title: 'الاستثمار الفندقي والجدوى',
        feat1Desc: 'نحن نعتمد قراراتك الاستثمارية على تحليلات السوق والطلب العوائد المالية.',
        feat1Item1: 'جدوى الاستثمار',
        feat1Item2: 'الحوافز وإصدار الشهادات',
        feat1Item3: 'تخطيط وإدارة المشاريع',
        feat2Title: 'تحسين الفنادق والتفوق التشغيلي',
        feat2Desc: 'خطة تحسين الفندق لزيادة الإيرادات والتحكم في التكاليف بشكل قابل للقياس.',
        feat2Item1: 'الإيرادات والتسعير',
        feat2Item2: 'العمليات والجودة',
        feat2Item3: 'المبيعات الرقمية والقنوات',
        feat3Title: 'دمج العلامات التجارية والإدارة',
        feat3Desc: 'الحصول على علامات تجارية عالمية، الامتياز التجاري والقيادة الاستراتيجية.',
        feat3Item1: 'اختيار العلامة التجارية',
        feat3Item2: 'هيكل المبيعات والتسويق',
        feat3Item3: 'استشارات الإدارة العامة',
        aboutSubtitle: 'عن الشركة',
        aboutTitle: 'نعمل لبناء مستقبل أكثر إشراقًا معًا و',
        aboutTitleSpan: 'تنمية الأعمال',
        missionTitle: 'مهمتنا',
        missionText: 'إعادة تعريف فن الضيافة من خلال دمج البيانات بالحكمة لتحويلها إلى نجاح مستدام.',
        visionTitle: 'رؤيتنا',
        visionText: 'أن نكون رفيقًا حكيمًا وعمليًا ومميزًا في قطاع الضيافة؛ نجمع بين البيانات والحكمة.',
        learnMore: 'اكتشف المزيد عنا',
        servicesSubtitle: 'استشارات الاستثمار وإدارة الفنادق',
        servicesTitle: 'دعم خبير من الاستراتيجية إلى التنفيذ الميداني',
        servicesDesc: 'من دراسات الجدوى ودمج العلامات التجارية إلى إدارة الإيرادات وتدقيق تحسين الفنادق.',
        satisfiedClients: 'المشاريع والفنادق المنجزة',
        exploreServices: 'استكشف كافة الخدمات',
        service1Title: 'الاستثمار الفندقي ودراسات الجدوى',
        service1Desc: 'تحليل الطلب والمنافسة لتعزيز صحة استثمارك.',
        service2Title: 'الامتياز ودمج العلامات التجارية',
        service2Desc: 'تحديد العلامة التجارية والشراكات الاستراتيجية الدولية.',
        service3Title: 'إدارة الإيرادات والمبيعات',
        service3Desc: 'التسعير، ووسائل الإيرادات لتحقيق ربحية مستدامة.',
        service4Title: 'تحسين الفنادق والتدقيق',
        service4Desc: 'خطة تحسين الفندق ومراقبة الجودة.',
        service5Title: 'وساطة الفنادق (بيع/شراء/إيجار)',
        service5Desc: 'تأسيس جسر حيوي بين المستثمرين وأصحاب الفنادق في قطاع الضيافة.',
        readMore: 'اقرأ المزيد',
        processSubtitle: 'عملية العمل',
        processTitle: 'من الفكرة إلى التنفيذ',
        processTitleSpan: 'عملنا الاستشاري',
        step1: 'الخطوة 01',
        step1Title: 'الاكتشاف والتقييم',
        step1Desc: 'تتضمن هذه المرحلة فهم احتياجات العميل والتحديات والأهداف.',
        step1Item1: 'جمع البيانات',
        step1Item2: 'تحليل الأعمال الشامل',
        step2: 'الخطوة 02',
        step2Title: 'تطوير الاستراتيجية',
        step2Desc: 'بناءً على البيانات المجمعة، نحدد مسارات مخصصة.',
        step2Item1: 'تخطيط الاستراتيجية',
        step2Item2: 'إدارة المخاطر',
        step3: 'الخطوة 03',
        step3Title: 'التنفيذ والإدارة',
        step3Desc: 'نقوم بتنفيذ الاستراتيجيات خطوة بخطوة.',
        step3Item1: 'إدارة المشاريع',
        step3Item2: 'تحسين الموارد',
        step4: 'الخطوة 04',
        step4Title: 'المراقبة والتحسين',
        step4Desc: 'نقيس النتائج ونقوم بالتحسينات اللازمة.',
        step4Item1: 'تتبع الأداء',
        step4Item2: 'تحسين مستمر',
        project1Title: 'تحسين أداء الأعمال',
        projectTag1: 'الشركات',
        projectTag2: 'الأعمال',
        projectTag3: 'المالية',
        teamMarquee: 'تعرف على فريق خبرائنا',
        teamSubtitle: 'تعرف على فريقنا',
        teamTitle: 'فريق',
        teamTitleSpan: 'الخبراء',
        exploreTeam: 'عرض جميع الأعضاء',
        consultant: 'مستشار أعمال',
        testimonialSubtitle: 'آراء العملاء',
        testimonialTitle: 'ماذا يقول',
        testimonialTitleSpan: 'عملاؤنا',
        counterSubtitle: 'أرقام نجاحنا',
        counterTitle: 'اختيار شركة استشارية موثوقة',
        counterTitleSpan: 'يغير عملك',
        counter1: 'المشاريع المنجزة',
        counter2: 'مستشارون خبراء',
        counter3: 'البلدان المخدومة',
        counter4: 'العملاء السعداء',
        blogSubtitle: 'اخر الاخبار',
        blogTitle: 'أحدث',
        blogTitleSpan: 'المقالات',
        readMoreLink: 'اقرأ المزيد',
        partnerSubtitle: 'شركاؤنا',
        partnerTitle: 'شركاء',
        partnerTitleSpan: 'موثوقون',
        faqTitle: 'الأسئلة',
        faqTitleSpan: 'الشائعة',
        s2FaqSubtitle: 'الأسئلة المتداولة',
        s2FaqTitle: 'حول',
        s2FaqTitleSpan: 'الاستشارات',
        s2Faq1Q: 'ما هي الخدمات التي تقدمونها للفنادق؟',
        s2Faq1A: 'نقدم استشارات من حيث الجدوى وصولاً إلى تحسين الفنادق.',
        s2Faq2Q: 'كيف تبدأ العملية الاستشارية؟',
        s2Faq2A: 'تبدأ باجتماع تقييمي ثم وضع خطة العمل.',
        s2Faq3Q: 'هل تعملون مع السلاسل الدولية فقط؟',
        s2Faq3A: 'لا، نحن نعمل مع جميع فئات الفنادق.',
        s2Faq4Q: 'ما هي خطة تحسين الفندق (HIP)؟',
        s2Faq4A: 'هي طريقة لتحليل أداء الفندق وإيجاد طرق لزيادة الأداء.',
        ctaTitle: 'هل أنت جاهز للبدء في خدماتنا الاستشارية؟',
        ctaBtn: 'استشارة مجانية',
        footerServices: 'خدماتنا',
        footerQuickLinks: 'روابط سريعة',
        footerService1: 'استشارات الاستثمار الفندقي',
        footerService2: 'دمج العلامات التجارية',
        footerService3: 'استشارات الإدارة',
        footerService4: 'استشارات التدقيق',
        footerService5: 'خطة تحسين الفندق',
        footerLink1: 'من نحن',
        footerLink2: 'الوظائف',
        footerLink3: 'التقديم',
        footerLink4: 'اتصل بنا',
        footerLink5: 'الحالات الدراسية',
        footerNewsletterDesc: 'اشترك في النشرة الإخبارية ليصلك كل جديد.',
        footerEmailPlaceholder: 'البريد الإلكتروني',
        footerSubscribe: 'اشتراك',
        footerCTA1Caption: 'تصبح عضوا في الفريق؟',
        footerCTA1Desc: 'نحن نبحث دائما عن الموهوبين',
        footerCTA1Btn: 'ابدأ الآن',
        footerCTA2Caption: 'هل تحتاج إلى استشارة عالية الجودة؟',
        footerCTA2Desc: 'نحن دائمًا في الخدمة',
        footerCTA2Btn: 'احصل على استشارة',
        footerCTA3Caption: 'هل تبحث عن عمل؟',
        footerCTA3Desc: 'نحن نبحث دائما عن الموهوبين',
        footerCTA3Btn: 'انضم إلينا',
        footerCopyright: 'جميع الحقوق محفوظة',
        footerTerms: 'شروط الاستخدام',
        footerPrivacy: 'سياسة الخصوصية',
        contactUs: 'اتصل بنا',
        address: 'العنوان',
        email: 'البريد',
        call: 'الهاتف',
        s2Subtitle: 'لماذا تختارنا',
        s2Title: 'الخبرة المتميزة في',
        s2TitleSpan: 'نجاح أعمالك',
        s2Desc: 'نحن ملتزمون بتقديم أفضل الخدمات الاستشارية لاحتياجاتك.',
        s2Item1: 'خبرة، كفاءة، ونتائج',
        s2Item2: 'الخيار الذكي للتميز في الاستشارات',
        s2Explore: 'اكتشف خدماتنا',
        s2SmartChoice: 'الخيار الذكي للتميز',
        s2Solution1Title: 'حلول مخصصة',
        s2Solution1Desc: 'نقدم حلولاً مخصصة لتلبية الاحتياجات المختلفة.',
        s2Solution2Title: 'القرارات المعتمدة على البيانات',
        s2Solution2Desc: 'نستفيد من البيانات لوضع الاستراتيجيات المناسبة.',
        s2Solution3Title: 'نتائج مستدامة',
        s2Solution3Desc: 'استراتيجيات فعالة تضمن الاستدامة على المدى الطويل.',
        s2ConsultingSubtitle: 'خدمات الاستشارة',
        s2ConsultingTitle: 'الاستشارة الأفضل لتطوير',
        s2ConsultingTitleSpan: 'أعمالك',
        s2ManagementTitle: 'الاستشارة الإدارية',
        s2ManagementDesc: 'نساعد الشركات في تحسين المهارات الإدارية.',
        s2ResourcesTitle: 'استشارة الموارد',
        s2ResourcesDesc: 'تحسين الموارد للشركات بفاعلية.',
        s2MarketingTitle: 'الاستشارة التسويقية',
        s2MarketingDesc: 'تحسين خطط التسويق وزيادة المبيعات.',
        s2FinancialTitle: 'الاستشارة المالية',
        s2FinancialDesc: 'توفير التخطيط المالي وتخفيض المخاطر.',
        s2DigitalTitle: 'التحول الرقمي',
        s2DigitalDesc: 'نوفر الحلول الرقمية وندرب الشركات عليها.',
        s2OperationsTitle: 'إدارة العمليات',
        s2OperationsDesc: 'نوفر إدارة العمليات لتخفيض التكاليف.',
        s2Faq1Q: 'ما هي استشارات الأعمال؟',
        s2Faq1A: 'تبدأ العملية بتقييم متطلبات العمل و وضع خطط التنفيذ.',
        s2Faq2Q: 'كيف تسير عملية الاستشارة؟',
        s2Faq2A: 'نقوم بالتحليل و من ثم التصميم و في النهاية التنفيذ.',
        s2Faq3Q: 'أي الفئات تتولون مراجعتها؟',
        s2Faq3A: 'كافة أنواع الشركات سواء الناشئة أو الكبيرة.',
        s2Faq4Q: 'ما هي تكلفة الخدمات؟',
        s2Faq4A: 'تعتمد على المشروع والاحتياجات.',
        s2SatisfiedCustomer: 'رضا العملاء',
        s2SatisfiedDesc: 'العملاء السعداء بالخدمات المتميزة',
        s2Marquee1: 'هل تحتاج لخدمة مخصصة؟',
        s2MarqueeContact: 'اتصل بنا',
        s2Marquee2: 'هل تريد الانضمام إلينا؟',
        s2MarqueeJoin: 'انضم إلينا',
        s2TestimonialSubtitle: 'آراء العملاء',
        s2TestimonialTitle: 'ماذا يقول عملاؤنا',
        s2TestimonialTitleSpan: 'عنا',
        s2TestimonialDesc: 'نساعد الشركات على تطوير استراتيجيات واضحة وقابلة للتنفيذ لتحقيق أهداف طويلة الأجل ونمو مستدام.',
        whyFieldTitle: 'خبرة ميدانية حقيقية',
        whyFieldDesc: 'نحن لا نقدم استشارات نظريًا فحسب، بل من خلال حكمة مستمدة من 40 عامًا من الخبرة القطاعية.',
        whyResultsTitle: 'نهج موجه نحو النتائج',
        whyResultsDesc: 'نحن لا نسأل "هل يبدو الفندق جيدًا؟" بل "هل يربح المال؟" كل خطوة قابلة للقياس.',
        whyServiceTitle: 'مجموعة خدمات شاملة',
        whyServiceDesc: 'نحن معك في جميع أبعاد الفندقة، من جدوى الاستثمار إلى تحسين الفنادق.',
        whyGlobalTitle: 'منظور عالمي ومحلي',
        whyGlobalDesc: 'لدينا خبرة عمل مباشرة مع علامات تجارية عملاقة مثل ماريوت وهيلتون وأكور.',
        faq1Q: 'مع من تعمل MISIONES؟',
        faq1A: 'نعمل مع مستثمري الفنادق، ورواد الأعمال، ومشغلي الفنادق الحاليين وجميع أصحاب المصلحة.',
        faq2Q: 'ما هو HIP ولمن تم تصميمه؟',
        faq2A: 'HIP (خطة تحسين الفندق) هي حزمة استشارية خاصة تحدد وتحل خسائر الإيرادات وعدم الكفاءة التشغيلية.',
        faq3Q: 'كيف تبدأ العملية الاستشارية؟',
        faq3A: 'نبدأ باجتماع تمهيدي مجاني. نستمع إلى الوضع الحالي للفندق وأهدافه ومشكلاته.',
        faq4Q: 'هل لديكم خبرة في العمل مع ماركات الفنادق العالمية؟',
        faq4A: 'نعم. لدينا خبرة عمل مباشرة مع ماريوت وهيلتون وويندام وأكور والعديد من العلامات الأخرى.',
        faq5Q: 'هل تعملون مع الفنادق فقط؟',
        faq5A: 'خبرتنا الأساسية هي قطاع الضيافة، ولكننا نقدم أيضًا استشارات للمشاريع المختلطة.',
        faq6Q: 'هل تقومون بمتابعة التنفيذ بعد الاستشارة؟',
        faq6A: 'نعم. نحن نراقب بنشاط نتائج التنفيذ من خلال تتبع مؤشرات الأداء والاجتماعات الدورية.',
        contactTitle: 'أرسل طلب استشارة',
        contactDesc: 'أرسل لنا مشروعك أو سؤالك أو عرض تعاونك. سنرد عليك في أقرب وقت ممكن.',
        msgReceived: 'تم استلام رسالتك!',
        msgSuccess: 'سنتواصل معك في أقرب وقت ممكن.',
        formName: 'الاسم الكامل *',
        formPhone: 'الهاتف *',
        formEmail: 'البريد الإلكتروني *',
        formSubject: 'الموضوع',
        formMsg: 'اكتب رسالتك هنا...',
        formSend: 'إرسال الرسالة',
        formOr: 'أو اكتب مباشرة: ',
    },
    ru: {
        topbarWelcome: 'Добро пожаловать в консалтинговое агентство',
        workingHours: 'Часы работы: 09:00 - 18:00',
        getInTouch: 'Связаться с нами',
        navHome: 'Главная',
        navPages: 'Страницы',
        navAbout: 'О нас',
        navServices: 'Услуги',
        navCase: 'Проекты',
        navBlog: 'Блог',
        navContact: 'Контакты',
        navTeamMember: 'Команда',
        navTeamDetails: 'Сведения о команде',
        navPricing: 'Цены',
        navCareer: 'Карьера',
        navAwards: 'Награды',
        navMissionVision: 'Миссия и Видение',
        navFaqs: 'Часто задаваемые вопросы',
        navOurService: 'Наши услуги',
        navOurService2: 'Наши услуги 02',
        navServiceDetails: 'Сведения об услуге',
        navCaseStudy1: 'Ревю проекта 01',
        navCaseStudy2: 'Ревю проекта 02',
        navCaseDetails: 'Сведения о проекте',
        navBlogStandard: 'Блог',
        navBlogDetails: 'Сведения о блоге',
        heroSubtitle: 'Консалтинг в сфере гостеприимства',
        heroTitle: 'Современный бизнес',
        heroTitleAnd: 'Консалтинг',
        heroWord1: 'Услуги',
        heroWord2: 'Решения',
        heroWord3: 'Стратегия',
        heroWord4: 'Аудит',
        heroDesc: 'Стратегический консалтинг в индустрии гостеприимства на основе инвестиций, интеграции брендов, управления доходами и планов улучшения отелей (HIP).',
        heroBtn: 'Изучить услуги',
        heroVideo: 'Смотреть видео',
        handwritingQuote: '"Мы предлагаем лучшее для вашего успеха"',
        marqueeText: 'Hospitality Global Experience Works & Green Horizon Hotels EcoSphere Consultance',
        feat1Title: 'Инвестиции и Технико-экономическое обоснование',
        feat1Desc: 'Обосновываем инвестиции рыночным, финансовым и потребительским анализами.',
        feat1Item1: 'Инвестиционная целесообразность',
        feat1Item2: 'Стимулирование и сертификация',
        feat1Item3: 'Проектное управление',
        feat2Title: 'План Улучшений и Операционное Совершенство (HIP)',
        feat2Desc: 'HIP: увеличение прибыли, оптимизация затрат и процессов.',
        feat2Item1: 'Доходы и ценообразование',
        feat2Item2: 'Операции и качество',
        feat2Item3: 'Цифровые продажи и каналы',
        feat3Title: 'Бренд и Управление',
        feat3Desc: 'Приобретение международных брендов, франчайзинг и стратегическое лидерство.',
        feat3Item1: 'Выбор и регистрация бренда',
        feat3Item2: 'Структура маркетинга и продаж',
        feat3Item3: 'Генеральный консалтинг',
        aboutSubtitle: 'о компании',
        aboutTitle: 'Мы Работаем, Чтобы Строить Светлое Будущее Вместе и',
        aboutTitleSpan: 'Развивать Бизнес',
        missionTitle: 'Наша Миссия',
        missionText: 'Переосмыслить искусство гостеприимства, объединив данные с мудростью для обеспечения устойчивого успеха.',
        visionTitle: 'Наше Видение',
        visionText: 'Быть уникальным, достоверным и мудрым проводником в индустрии гостеприимства.',
        learnMore: 'Узнать о нас больше',
        servicesSubtitle: 'консалтинг по инвестициям и управлению',
        servicesTitle: 'Экспертная Поддержка: от Стратегии до Реализации',
        servicesDesc: 'Охватываем всю цепочку создания стоимости: от ТЭО до управления доходами, аудита и HIP.',
        satisfiedClients: 'Успешные Проекты',
        exploreServices: 'Изучить Все Услуги',
        service1Title: 'Инвестиции и ТЭО',
        service1Desc: 'Анализ спроса, конкуренции и финансовое моделирование для вашего проекта.',
        service2Title: 'Интеграция Брендов и Франчайзинг',
        service2Desc: 'Юридическая защита и стратегическое партнерство с международными сетями.',
        service3Title: 'Управление Доходами и Продажами',
        service3Desc: 'Ценообразование, рост прямых продаж и оптимизация RMS/CRM для стабильной прибыли.',
        service4Title: 'HIP, Аудит и Устойчивость',
        service4Desc: 'План Улучшения Отеля (HIP), финансовый и операционный аудит, контроль рисков.',
        service5Title: 'Брокеридж (Покупка / Продажа / Аренда)',
        service5Desc: 'Связующее звено между инвесторами и владельцами отелей. Предоставляем экспертные брокерские услуги.',
        readMore: 'Читать далее',
        processSubtitle: 'рабочий процесс',
        processTitle: 'От Концепции к Исполнению',
        processTitleSpan: 'Наш Процесс Консалтинга',
        step1: 'Шаг 01',
        step1Title: 'Изучение и Оценка',
        step1Desc: 'Понимание потребностей, целей и вызовов клиента. Экспертный анализ.',
        step1Item1: 'Сбор данных',
        step1Item2: 'Глобальный анализ бизнеса',
        step2: 'Шаг 02',
        step2Title: 'Разработка Стратегии',
        step2Desc: 'Определение индивидуального плана развития на основе полученных данных.',
        step2Item1: 'Стратегическое планирование',
        step2Item2: 'Управление рисками',
        step3: 'Шаг 03',
        step3Title: 'Внедрение и Исполнение',
        step3Desc: 'Поэтапное применение стратегий и мониторинг процессов.',
        step3Item1: 'Управление проектом',
        step3Item2: 'Оптимизация ресурсов',
        step4: 'Шаг 04',
        step4Title: 'Мониторинг и Улучшение',
        step4Desc: 'Непрерывное отслеживание результатов и внедрение улучшений.',
        step4Item1: 'Отслеживание метрик',
        step4Item2: 'Непрерывная оптимизация',
        project1Title: 'Оптимизация Эффективности Бизнеса',
        projectTag1: 'Корпоративный',
        projectTag2: 'Бизнес',
        projectTag3: 'Финансы',
        teamMarquee: 'ВСТРЕЧАЙТЕ НАШУ КОМАНДУ',
        teamSubtitle: 'Познакомьтесь с нами',
        teamTitle: 'Команда',
        teamTitleSpan: 'Экспертов',
        exploreTeam: 'Все участники команды',
        consultant: 'Бизнес-консультант',
        testimonialSubtitle: 'отзывы клиентов',
        testimonialTitle: 'Наши Клиенты',
        testimonialTitleSpan: 'Обзор',
        counterSubtitle: 'ПОКАЗАТЕЛИ УСПЕХА',
        counterTitle: 'Выбор Надежной Консалтинговой Компании',
        counterTitleSpan: 'Трансформирует Ваш Бизнес',
        counter1: 'Успешных проектов',
        counter2: 'Экспертов',
        counter3: 'Стран присутствия',
        counter4: 'Довольных клиентов',
        blogSubtitle: 'ПОСЛЕДНИЕ НОВОСТИ',
        blogTitle: 'Последние Статьи',
        blogTitleSpan: 'В Блоге',
        readMoreLink: 'Читать далее',
        partnerSubtitle: 'НАШИ ПАРТНЕРЫ',
        partnerTitle: 'Надежные',
        partnerTitleSpan: 'Партнеры',
        faqTitle: 'Часто Задаваемые',
        faqTitleSpan: 'Вопросы',
        s2FaqSubtitle: 'Часто Задаваемые Вопросы',
        s2FaqTitle: 'О Нашем',
        s2FaqTitleSpan: 'Консалтинге',
        s2Faq1Q: 'Какие услуги вы предоставляете отелям?',
        s2Faq1A: 'Мы предлагаем широкий спектр услуг, от ТЭО до интеграции брендов и управления доходами.',
        s2Faq2Q: 'Как начинается процесс консалтинга?',
        s2Faq2A: 'Процесс начинается с вводной встречи и переходит в индивидуальную дорожную карту развития.',
        s2Faq3Q: 'Работаете ли вы только с международными сетями?',
        s2Faq3A: 'Нет. Мы работаем с бутиками, курортами и сетевыми отелями любого масштаба.',
        s2Faq4Q: 'Что такое План Улучшения Отеля (HIP)?',
        s2Faq4A: 'Методика сканирования эффективности вашего отеля и создание планов по ее улучшению.',
        ctaTitle: 'Готовы Начать Работу с Нашими Экспертами?',
        ctaBtn: 'Бесплатная Консультация',
        footerServices: 'Наши Услуги',
        footerQuickLinks: 'Быстрые Ссылки',
        footerService1: 'Инвестиционный Консалтинг',
        footerService2: 'Интеграция Брендов',
        footerService3: 'Управленческий Консалтинг',
        footerService4: 'Аудит и Контроль',
        footerService5: 'План Улучшений (HIP)',
        footerLink1: 'О Компании',
        footerLink2: 'Карьера',
        footerLink3: 'Заявки',
        footerLink4: 'Связаться с нами',
        footerLink5: 'Проекты',
        footerNewsletterDesc: 'Подпишитесь на нашу рассылку, чтобы получать последние новости.',
        footerEmailPlaceholder: 'Email Адрес',
        footerSubscribe: 'Подписаться',
        footerCTA1Caption: 'Хотите Работать с Нами?',
        footerCTA1Desc: 'Мы всегда ищем таланты',
        footerCTA1Btn: 'Начать Работу',
        footerCTA2Caption: 'Нужна Экспертная Поддержка?',
        footerCTA2Desc: 'Мы готовы к новым вызовам',
        footerCTA2Btn: 'Получить Консультацию',
        footerCTA3Caption: 'Ищете Работу?',
        footerCTA3Desc: 'Мы ждем талантливых кандидатов',
        footerCTA3Btn: 'Присоединиться',
        footerCopyright: 'Все Права Защищены',
        footerTerms: 'Условия Использования',
        footerPrivacy: 'Политика Конфиденциальности',
        contactUs: 'Связаться с Нами',
        address: 'Адрес',
        email: 'Email',
        call: 'Телефон',
        s2Subtitle: 'почему выбирают нас',
        s2Title: 'Непревзойденный Опыт Для',
        s2TitleSpan: 'Вашего Бизнеса',
        s2Desc: 'Мы предоставляем качественные консалтинговые услуги для достижения результатов.',
        s2Item1: 'Опыт, Экспертиза и Результаты',
        s2Item2: 'Умный Выбор Для Развития Вашего Бизнеса',
        s2Explore: 'Ознакомиться С Услугами',
        s2SmartChoice: 'Лучший Выбор В Бизнес Консалтинге',
        s2Solution1Title: 'Индивидуальные Решения',
        s2Solution1Desc: 'Мы разрабатываем персонализированные стратегии под конкретные задачи.',
        s2Solution2Title: 'Подход На Основе Данных',
        s2Solution2Desc: 'Для надежных стратегий мы используем мощную аналитику.',
        s2Solution3Title: 'Устойчивые Результаты',
        s2Solution3Desc: 'Долгосрочные результаты, которые ведут ваш бизнес к росту.',
        s2ConsultingSubtitle: 'услуги консалтинга',
        s2ConsultingTitle: 'Консалтинг Высшего Качества Для Роста',
        s2ConsultingTitleSpan: 'Бизнеса',
        s2ManagementTitle: 'Управленческий Консалтинг',
        s2ManagementDesc: 'Услуги по раскрытию потенциала бизнеса.',
        s2ResourcesTitle: 'Консалтинг по Ресурсам',
        s2ResourcesDesc: 'Оптимизация управления всеми ресурсами компании.',
        s2MarketingTitle: 'Маркетинговый Консалтинг',
        s2MarketingDesc: 'Адаптация маркетинговых усилий.',
        s2FinancialTitle: 'Финансовый Консалтинг',
        s2FinancialDesc: 'Долгосрочное планирование и финансовый менеджмент.',
        s2DigitalTitle: 'Цифровая Трансформация',
        s2DigitalDesc: 'Предоставление цифровых инструментов и процессов.',
        s2OperationsTitle: 'Операционный Менеджмент',
        s2OperationsDesc: 'Анализ внутренних процессов и повышение эффективности.',
        s2Faq1Q: 'Что такое бизнес консалтинг?',
        s2Faq1A: 'Оценка ваших потребности и создание индивидуального плана.',
        s2Faq2Q: 'Как осуществляется процесс?',
        s2Faq2A: 'Мы следуем системному подходу с отслеживанием показателей.',
        s2Faq3Q: 'С какими компаниями вы работаете?',
        s2Faq3A: 'Как со стартапами, так и с крупными международными брендами.',
        s2Faq4Q: 'Сколько стоят ваши услуги?',
        s2Faq4A: 'Затраты зависят от сложности и масштаба проекта.',
        s2SatisfiedCustomer: 'Оценка Качества',
        s2SatisfiedDesc: 'Отзывы Довольных Клиентов',
        s2Marquee1: 'Нужна Специальная Услуга?',
        s2MarqueeContact: 'Контакты',
        s2Marquee2: 'Хочешь Присоединиться к Команде?',
        s2MarqueeJoin: 'Присоединиться к Нам',
        s2TestimonialSubtitle: 'отзывы клиентов',
        s2TestimonialTitle: 'Что Клиенты Говорят О',
        s2TestimonialTitleSpan: 'Нас',
        s2TestimonialDesc: 'Разработка долгосрочных и надежных бизнес-стратегий.',
        whyFieldTitle: 'Реальный полевой опыт',
        whyFieldDesc: 'Мы консультируем не только по теории, но и опираясь на мудрость 40-летнего опыта.',
        whyResultsTitle: 'Результативный подход',
        whyResultsDesc: 'Мы спрашиваем не "хорошо ли выглядит отель?", а "приносит ли он деньги?".',
        whyServiceTitle: 'Комплексный спектр услуг',
        whyServiceDesc: 'Мы с вами на всех этапах: от ТЭО до улучшения отеля (HIP).',
        whyGlobalTitle: 'Глобальная и локальная перспектива',
        whyGlobalDesc: 'У нас есть прямой опыт работы с такими гигантами, как Marriott, Hilton, Accor.',
        faq1Q: 'С кем работает MISIONES?',
        faq1A: 'Мы работаем с инвесторами, предпринимателями и операторами отелей.',
        faq2Q: 'Что такое HIP и для кого он предназначен?',
        faq2A: 'HIP (План улучшения отеля) — это пакет, который выявляет и решает проблемы доходности.',
        faq3Q: 'Как начинается процесс консалтинга?',
        faq3A: 'Мы начинаем с бесплатной предварительной встречи для анализа текущей ситуации.',
        faq4Q: 'Есть ли у вас опыт работы с международными брендами?',
        faq4A: 'Да, мы работали напрямую с Marriott, Hilton, Wyndham, Accor и другими брендами.',
        faq5Q: 'Вы работаете только с отелями?',
        faq5A: 'Наша основная специализация — гостеприимство, но мы консультируем и смешанные проекты.',
        faq6Q: 'Вы следите за внедрением после консультации?',
        faq6A: 'Да, мы активно отслеживаем результаты через KPI и периодические встречи.',
        contactTitle: 'Отправить запрос на консультацию',
        contactDesc: 'Сообщите нам о своем проекте или вопросе. Мы ответим как можно скорее.',
        msgReceived: 'Ваше сообщение получено!',
        msgSuccess: 'Мы свяжемся с вами в ближайшее время.',
        formName: 'Имя Фамилия *',
        formPhone: 'Телефон *',
        formEmail: 'Email *',
        formSubject: 'Тема',
        formMsg: 'Напишите ваше сообщение здесь...',
        formSend: 'Отправить сообщение',
        formOr: 'или напишите напрямую: ',
    }
}

export function LanguageProvider({ children }) {
    const [lang, setLang] = useState('tr')

    const t = (key) => {
        if (translations[lang] && translations[lang][key]) return translations[lang][key]
        if (translations.en && translations.en[key]) return translations.en[key]
        if (translations.tr && translations.tr[key]) return translations.tr[key]
        return key
    }

    const toggleLang = () => setLang(prev => {
        const order = ['tr', 'en', 'ar', 'ru']
        const idx = order.indexOf(prev)
        return order[(idx + 1) % order.length]
    })

    return (
        <LanguageContext.Provider value={{ lang, setLang, t, toggleLang }}>
            {children}
        </LanguageContext.Provider>
    )
}

export function useLanguage() {
    return useContext(LanguageContext)
}
