'use client'
import { createContext, useContext, useState } from 'react'

const LanguageContext = createContext()

export const translations = {
    tr: {
        // Topbar
        topbarWelcome: 'Ödüllü Danışmanlık Firmasına Hoş Geldiniz',
        workingHours: 'Çalışma Saatleri: 09:00 - 18:00',
        // Header
        getInTouch: 'İletişime Geç',
        // Navigation
        navHome: 'Ana Sayfa',
        navPages: 'Sayfalar',
        navAbout: 'Hakkımızda',
        navServices: 'Hizmetler',
        navCase: 'Projeler',
        navBlog: 'Blog',
        navContact: 'İletişim',
        navTeamMember: 'Ekip Üyeleri',
        navTeamDetails: 'Ekip Detayı',
        navPricing: 'Fiyatlandırma',
        navCareer: 'Kariyer',
        navAwards: 'Ödüller',
        navMissionVision: 'Misyon & Vizyon',
        navFaqs: 'SSS',
        navOurService: 'Hizmetlerimiz',
        navOurService2: 'Hizmetlerimiz 02',
        navServiceDetails: 'Hizmet Detayı',
        navCaseStudy1: 'Proje Çalışması 01',
        navCaseStudy2: 'Proje Çalışması 02',
        navCaseDetails: 'Proje Detayı',
        navBlogStandard: 'Blog',
        navBlogDetails: 'Blog Detayı',
        // Hero
        heroSubtitle: 'hospitality danışmanlık firması',
        heroTitle: 'Modern İş',
        heroTitleAnd: 'Danışmanlığı',
        heroWord1: 'Hizmetleri',
        heroWord2: 'Çözümleri',
        heroWord3: 'Stratejisi',
        heroDesc: 'Otel yatırımı, marka entegrasyonu, gelir yönetimi ve HIP ile turizm ve otelcilikte sahadan gelen stratejik danışmanlık sunuyoruz.',
        heroBtn: 'Hizmetleri Keşfet',
        heroVideo: 'Videoyu İzle',
        handwritingQuote: '"Başarınız için elimizden gelenin en iyisini sağlıyoruz"',
        marqueeText: 'Hospitality Global Experience Works & Green Horizon Hotels EcoSphere Consultance',
        // Section 1 - Features
        feat1Title: 'Otel Yatırım & Fizibilite',
        feat1Desc: 'Piyasa, talep ve finansal geri dönüş analizleriyle yatırım kararınızı veriye dayandırıyoruz.',
        feat1Item1: 'Yatırım fizibilitesi',
        feat1Item2: 'Teşvik ve belgelendirme',
        feat1Item3: 'Proje planlama ve yönetimi',
        feat2Title: 'HIP & Operasyonel Mükemmellik',
        feat2Desc: 'Hotel Improvement Plan ile gelir, maliyet ve süreçleri ölçülebilir biçimde iyileştiriyoruz.',
        feat2Item1: 'Gelir ve fiyatlandırma',
        feat2Item2: 'Operasyon ve kalite',
        feat2Item3: 'Kanal ve dijital satış',
        feat3Title: 'Marka & Yönetim Entegrasyonu',
        feat3Desc: 'Uluslararası marka alımı, franchising ve stratejik yönetimle otelinizi konumlandırıyoruz.',
        feat3Item1: 'Marka seçimi ve tescil',
        feat3Item2: 'Satış ve pazarlama yapısı',
        feat3Item3: 'Genel yönetim danışmanlığı',
        // Section 2 - About
        aboutSubtitle: 'hakkımızda',
        aboutTitle: 'Birlikte Daha Aydınlık Bir Gelecek İnşa Ediyor ve',
        aboutTitleSpan: 'İşinizi Büyütüyoruz',
        missionTitle: 'Misyonumuz',
        missionText: 'Otelcilik sanatını yeniden tanımlamak, veriyi bilgelikle birleştirerek sürdürülebilir başarıya dönüştürmek. Her oteli yalnızca bugünün rekabetine değil, yarının belirsizliğine karşı da güçlendirmek.',
        visionTitle: 'Vizyonumuz',
        visionText: 'Otelcilik sektöründe fark yaratan, özgün, sahici ve bilge bir yol arkadaşı olarak; veriyi bilgelikle, stratejiyi hikâyeyle, operasyonu sanatla buluşturmak.',
        learnMore: 'Hakkımızda Daha Fazla',
        // Section 3 - Services
        servicesSubtitle: 'otel yatırım ve yönetim danışmanlığı',
        servicesTitle: 'Otelcilikte Stratejiden Sahaya Uzman Destek',
        servicesDesc: 'Yatırım fizibilitesinden marka entegrasyonuna, gelir yönetiminden denetim ve HIP uygulamalarına kadar otelciliğin tüm değer zincirinde yanınızdayız.',
        satisfiedClients: 'Tamamlanan Proje & Otel',
        exploreServices: 'Tüm Hizmetleri Keşfet',
        service1Title: 'Otel Yatırım & Fizibilite Danışmanlığı',
        service1Desc: 'Talep, rekabet ve finansal modelleme ile yatırımınızın doğruluğunu güçlendiriyoruz.',
        service2Title: 'Marka Entegrasyonu & Franchising',
        service2Desc: 'Marka belirleme, hukuki koruma ve uluslararası zincirlerle stratejik işbirlikleri.',
        service3Title: 'Gelir Yönetimi & Satış-Pazarlama',
        service3Desc: 'Fiyatlandırma, kanal karması, RMS/CRM uyumu ve doğrudan satışlarla sürdürülebilir kârlılık.',
        service4Title: 'HIP, Denetim & Sürdürülebilirlik',
        service4Desc: 'Hotel Improvement Plan, operasyonel ve mali denetim ile kalite ve risk yönetimi.',
        readMore: 'Devamını Oku',
        // Section 4 - Process
        processSubtitle: 'çalışma süreci',
        processTitle: 'Fikirden Uygulamaya',
        processTitleSpan: 'Danışmanlık Sürecimiz',
        step1: 'Adım 01',
        step1Title: 'Keşif & Değerlendirme',
        step1Desc: 'Bu ilk aşamada müşterinin ihtiyaçlarını, zorluklarını ve hedeflerini anlıyoruz. Danışmanlar derinlemesine analiz yapıyor.',
        step1Item1: 'Paydaş Görüşmeleri & Veri Toplama',
        step1Item2: 'Kapsamlı İş Analizi',
        step2: 'Adım 02',
        step2Title: 'Strateji Geliştirme',
        step2Desc: 'Toplanan veriler ışığında özelleştirilmiş stratejiler ve çözüm yolları belirliyoruz.',
        step2Item1: 'Özel Strateji Planlaması',
        step2Item2: 'Risk Değerlendirmesi ve Yönetimi',
        step3: 'Adım 03',
        step3Title: 'Uygulama & Yürütme',
        step3Desc: 'Geliştirilen stratejileri adım adım hayata geçiriyor, süreçleri takip ediyoruz.',
        step3Item1: 'Proje Yönetimi & Koordinasyon',
        step3Item2: 'Kaynak Optimizasyonu',
        step4: 'Adım 04',
        step4Title: 'İzleme & Sürekli İyileştirme',
        step4Desc: 'Sonuçları sürekli ölçüyor ve gerekli iyileştirmeleri yaparak uzun vadeli başarıyı güvence altına alıyoruz.',
        step4Item1: 'Performans Metrikleri Takibi',
        step4Item2: 'Sürekli Optimizasyon',
        // Section 5 - Projects
        project1Title: 'İş Performansını Optimize Etme',
        projectTag1: 'Kurumsal',
        projectTag2: 'İş',
        projectTag3: 'Finans',
        // Section 6 - Team
        teamMarquee: 'uzman ekibimizle tanışın',
        teamSubtitle: 'Ekibimizle Tanışın',
        teamTitle: 'Uzman Ekip',
        teamTitleSpan: 'Üyeleri',
        exploreTeam: 'Tüm Üyeleri Görüntüle',
        consultant: 'İş Danışmanı',
        // Section 7 - Testimonials  
        testimonialSubtitle: 'müşteri yorumları',
        testimonialTitle: 'Müşterilerimizin',
        testimonialTitleSpan: 'Görüşleri',
        // Section 8 - Counter
        counterSubtitle: 'başarı rakamlarımız',
        counterTitle: 'Güvenilir Bir Danışmanlık Firmasını Seçmek',
        counterTitleSpan: 'İşletmenizi Dönüştürür',
        counter1: 'Tamamlanan Proje',
        counter2: 'Uzman Danışman',
        counter3: 'Ülkede Faaliyet',
        counter4: 'Memnun Müşteri',
        // Section 9 - Blog
        blogSubtitle: 'son haberler',
        blogTitle: 'En Son Blog',
        blogTitleSpan: 'Yazılarımız',
        readMoreLink: 'Devamını Oku',
        // Section 10 - Partners
        partnerSubtitle: 'iş ortaklarımız',
        partnerTitle: 'Güvenilen',
        partnerTitleSpan: 'İş Ortakları',
        // Section 11 - FAQ
        faqSubtitle: 'sık sorulan sorular',
        faqTitle: 'Sıkça Sorulan',
        faqTitleSpan: 'Sorular',
        // Section 12 - CTA
        ctaTitle: 'Danışmanlık Hizmetlerimize Başlamaya Hazır mısınız?',
        ctaBtn: 'Ücretsiz Danışın',
        // Footer
        footerServices: 'Hizmetlerimiz',
        footerQuickLinks: 'Hızlı Bağlantılar',
        footerService1: 'Otel Yatırım Danışmanlığı',
        footerService2: 'Marka Entegrasyonu',
        footerService3: 'Otel Yönetim Danışmanlığı',
        footerService4: 'Otel Denetim Danışmanlığı',
        footerService5: 'HIP - Hotel Improvement Plan',
        footerLink1: 'Hakkımızda',
        footerLink2: 'Kariyer Fırsatları',
        footerLink3: 'Başvurular',
        footerLink4: 'İletişim',
        footerLink5: 'Proje Çalışmaları',
        footerNewsletterDesc: 'Dijital pazarlama alanındaki en son trendlerden haberdar olmak ve özel ipuçları almak için bültenimize abone olun.',
        footerEmailPlaceholder: 'E-posta Adresiniz',
        footerSubscribe: 'Abone Ol',
        footerCTA1Caption: 'Ekip Üyesi Olmak İster misiniz?',
        footerCTA1Desc: 'Her zaman yetenekli adaylar arıyoruz',
        footerCTA1Btn: 'Hemen Başla',
        footerCTA2Caption: 'Kaliteli Danışmanlığa mı İhtiyacınız Var?',
        footerCTA2Desc: 'Her zaman yetenekli adaylar arıyoruz',
        footerCTA2Btn: 'Danışmanlık Al',
        footerCTA3Caption: 'İş Fırsatı mı Arıyorsunuz?',
        footerCTA3Desc: 'Her zaman yetenekli adaylar arıyoruz',
        footerCTA3Btn: 'Bize Katılın',
        footerCopyright: 'Tüm Hakları Saklıdır',
        footerTerms: 'Kullanım Koşulları',
        footerPrivacy: 'Gizlilik Politikası',
        // Contact info
        contactUs: 'İletişim',
        address: 'Adres',
        email: 'E-posta',
        call: 'Telefon',
    },
    en: {
        // Topbar
        topbarWelcome: 'Welcome to Award Winning Consulting Agency',
        workingHours: 'Working Hours: 09am - 06pm',
        // Header
        getInTouch: 'Get In Touch',
        // Navigation
        navHome: 'Home',
        navPages: 'Pages',
        navAbout: 'About',
        navServices: 'Services',
        navCase: 'Case',
        navBlog: 'Blog',
        navContact: 'Contact',
        navTeamMember: 'Team Member',
        navTeamDetails: 'Team Details',
        navPricing: 'Pricing Table',
        navCareer: 'Career',
        navAwards: 'Awards',
        navMissionVision: 'Mission Vision',
        navFaqs: 'FAQs',
        navOurService: 'Our Service',
        navOurService2: 'Our Service 02',
        navServiceDetails: 'Service Details',
        navCaseStudy1: 'Case Study 01',
        navCaseStudy2: 'Case Study 02',
        navCaseDetails: 'Case Details',
        navBlogStandard: 'Blog Standard',
        navBlogDetails: 'Blog Details',
        // Hero
        heroSubtitle: 'hospitality consulting agency',
        heroTitle: 'Modern Business',
        heroTitleAnd: 'Consulting',
        heroWord1: 'Services',
        heroWord2: 'Solutions',
        heroWord3: 'Strategy',
        heroDesc: 'Strategic hospitality consulting across investment, brand integration, revenue management and HIP — grounded in field experience.',
        heroBtn: 'Explore Services',
        heroVideo: 'Watch Video',
        handwritingQuote: '"We provide our best for your success"',
        marqueeText: 'Hospitality Global Experience Works & Green Horizon Hotels EcoSphere Consultance',
        // Section 1 - Features
        feat1Title: 'Hotel Investment & Feasibility',
        feat1Desc: 'We ground your investment decisions in market, demand and financial return analysis.',
        feat1Item1: 'Investment feasibility',
        feat1Item2: 'Incentives & certification',
        feat1Item3: 'Project planning & management',
        feat2Title: 'HIP & Operational Excellence',
        feat2Desc: 'Hotel Improvement Plan to measurably lift revenue, cost control and processes.',
        feat2Item1: 'Revenue & pricing',
        feat2Item2: 'Operations & quality',
        feat2Item3: 'Channel & digital sales',
        feat3Title: 'Brand & Management Integration',
        feat3Desc: 'International brand acquisition, franchising and strategic leadership for your hotel.',
        feat3Item1: 'Brand selection & registration',
        feat3Item2: 'Sales & marketing structure',
        feat3Item3: 'General management advisory',
        // Section 2 - About
        aboutSubtitle: 'about company',
        aboutTitle: 'We Work For Building a Brighter Future Together and',
        aboutTitleSpan: 'Grow Business',
        missionTitle: 'Our Mission',
        missionText: 'To redefine the art of hospitality; combining data with wisdom to turn it into sustainable success. To strengthen each hotel not just against today\'s competition, but also against tomorrow\'s uncertainty.',
        visionTitle: 'Our Vision',
        visionText: 'To be a unique, authentic, and wise companion that makes a difference in hospitality; bringing together data with wisdom, strategy with storytelling, and operations with artistry.',
        learnMore: 'Learn More About Us',
        // Section 3 - Services
        servicesSubtitle: 'hotel investment & management consulting',
        servicesTitle: 'Expert Support From Strategy to Field Execution',
        servicesDesc: 'From feasibility and brand integration to revenue management, audits and HIP — we cover the full hospitality value chain.',
        satisfiedClients: 'Projects & Hotels Delivered',
        exploreServices: 'Explore All Services',
        service1Title: 'Hotel Investment & Feasibility',
        service1Desc: 'Demand, competition and financial modelling to validate and strengthen your investment.',
        service2Title: 'Brand Integration & Franchising',
        service2Desc: 'Brand definition, legal protection and strategic partnerships with international chains.',
        service3Title: 'Revenue Management & Sales-Marketing',
        service3Desc: 'Pricing, channel mix, RMS/CRM alignment and direct booking growth for sustainable profit.',
        service4Title: 'HIP, Audit & Sustainability',
        service4Desc: 'Hotel Improvement Plan plus operational and financial audits, quality and risk control.',
        readMore: 'Read More',
        // Section 4 - Process
        processSubtitle: 'working process',
        processTitle: 'From Concept to Execution',
        processTitleSpan: 'Our Consulting Process',
        step1: 'Step 01',
        step1Title: 'Discovery & Assessment',
        step1Desc: 'This initial phase involves understanding the client\'s needs, challenges, and goals. Consultants conduct in-depth analysis.',
        step1Item1: 'Stakeholder Interviews & Data Gathering',
        step1Item2: 'Comprehensive Business Analysis',
        step2: 'Step 02',
        step2Title: 'Strategy Development',
        step2Desc: 'Based on gathered data, we identify customized strategies and solution paths.',
        step2Item1: 'Custom Strategy Planning',
        step2Item2: 'Risk Assessment and Management',
        step3: 'Step 03',
        step3Title: 'Implementation & Execution',
        step3Desc: 'We implement the developed strategies step by step and monitor the processes.',
        step3Item1: 'Project Management & Coordination',
        step3Item2: 'Resource Optimization',
        step4: 'Step 04',
        step4Title: 'Monitoring & Continuous Improvement',
        step4Desc: 'We continuously measure results and make necessary improvements to ensure long-term success.',
        step4Item1: 'Performance Metrics Tracking',
        step4Item2: 'Continuous Optimization',
        // Section 5 - Projects
        project1Title: 'Optimizing Business Performance',
        projectTag1: 'Corporate',
        projectTag2: 'Business',
        projectTag3: 'Finance',
        // Section 6 - Team
        teamMarquee: 'meet our expert team',
        teamSubtitle: 'Meet Our Team',
        teamTitle: 'Expert Team',
        teamTitleSpan: 'Members',
        exploreTeam: 'Explore All Members',
        consultant: 'Business Consultant',
        // Section 7 - Testimonials  
        testimonialSubtitle: 'client testimonials',
        testimonialTitle: 'Our Clients',
        testimonialTitleSpan: 'Testimonials',
        // Section 8 - Counter
        counterSubtitle: 'our success numbers',
        counterTitle: 'Choosing a Trusted Consulting Firm',
        counterTitleSpan: 'Transforms Your Business',
        counter1: 'Projects Completed',
        counter2: 'Expert Consultants',
        counter3: 'Countries Served',
        counter4: 'Satisfied Clients',
        // Section 9 - Blog
        blogSubtitle: 'latest news',
        blogTitle: 'Latest Blog',
        blogTitleSpan: 'Articles',
        readMoreLink: 'Read More',
        // Section 10 - Partners
        partnerSubtitle: 'our partners',
        partnerTitle: 'Trusted',
        partnerTitleSpan: 'Partners',
        // Section 11 - FAQ
        faqSubtitle: 'frequently asked questions',
        faqTitle: 'Frequently Asked',
        faqTitleSpan: 'Questions',
        // Section 12 - CTA
        ctaTitle: 'Ready to Start with Our Consulting Services?',
        ctaBtn: 'Free Consultation',
        // Footer
        footerServices: 'Our Services',
        footerQuickLinks: 'Quick Links',
        footerService1: 'Hotel Investment Consulting',
        footerService2: 'Brand Integration',
        footerService3: 'Hotel Management Consulting',
        footerService4: 'Hotel Audit Consulting',
        footerService5: 'HIP - Hotel Improvement Plan',
        footerLink1: 'About Company',
        footerLink2: 'Career Options',
        footerLink3: 'Applications',
        footerLink4: 'Contact Us',
        footerLink5: 'Case Studies',
        footerNewsletterDesc: 'Stay up-to-date with the latest trends in digital marketing and receive exclusive tips and insights by subscribing to our newsletter.',
        footerEmailPlaceholder: 'Email Address',
        footerSubscribe: 'Subscribe',
        footerCTA1Caption: 'Become a Team Member?',
        footerCTA1Desc: 'We are always looking for talented members',
        footerCTA1Btn: 'Get Started',
        footerCTA2Caption: 'Need Quality Consultations?',
        footerCTA2Desc: 'We are always looking for talented members',
        footerCTA2Btn: 'Get Consultation',
        footerCTA3Caption: 'Are You Looking For A Job?',
        footerCTA3Desc: 'We are always looking for talented members',
        footerCTA3Btn: 'Join With Us',
        footerCopyright: 'All Rights Reserved',
        footerTerms: 'Terms & Conditions',
        footerPrivacy: 'Privacy Policy',
        // Contact info
        contactUs: 'Contact Us',
        address: 'Address',
        email: 'Email',
        call: 'Call',
    }
}

export function LanguageProvider({ children }) {
    const [lang, setLang] = useState('tr')

    const t = (key) => translations[lang][key] || key

    const toggleLang = () => setLang(prev => prev === 'tr' ? 'en' : 'tr')

    return (
        <LanguageContext.Provider value={{ lang, setLang, t, toggleLang }}>
            {children}
        </LanguageContext.Provider>
    )
}

export function useLanguage() {
    return useContext(LanguageContext)
}
